services:
  monitor:
    restart: unless-stopped
    build:
      context: ./monitoring
      dockerfile: Dockerfile.binary
    stop_grace_period: 30s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${MONITORING_PORT:-8080}:${MONITORING_PORT:-8080}/tcp
    logging: *logging
    environment:
      - NETWORK=${NETWORK}
      - MONITORING_PORT=${MONITORING_PORT:-8080}
      - RPC_ENDPOINT=${MONITORING_RPC_ENDPOINT:-http://consensus:26657}
      - DAEMON_NAME=sentinelhub
      - DAEMON_HOME=/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${MONITORING_PORT:-8080}/metrics"]
      interval: 60s
      timeout: 10s
      retries: 3
